apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST

  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    access: proxy
    orgId: 1
    url: timescaledb:5432
    database: karez
    user: karez
    secureJsonData:
      password: karez123
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    editable: true
